# permissions for end users to view ipv4addresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipv4address-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mikrotik-operator
    app.kubernetes.io/part-of: mikrotik-operator
    app.kubernetes.io/managed-by: kustomize
  name: ipv4address-viewer-role
rules:
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - ipv4addresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - routeros.mikrotik.com
  resources:
  - ipv4addresses/status
  verbs:
  - get
